addons:
  apt:
    packages:
    - realpath
language: python
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=joeblackwaslike
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=joeblackwaslike
  # DOCKER_PASS
  - secure: "KiS+e1WAeKLPeAafJhiqgoacvu0tE9KWShYnHnE660E+T7StAnh8lP+Cg2QmVNLB5ZIfaoLgaCIbPfgiG8fN3v1kzcgCQkVP5Zou2i+r0iiOTwK4si3EgSi51S8HOMwVtUm4WOQoBVO2weKT6/OsdUdis06e5eqysjC4hsFLiQmdXDt840Opn96yeCQwM5HchOBeI5VlWryBDphIDv+9mdkQ/cYMHepTBriBfUWBkh+safwWcAtN6fJnipix3EVKyyXwxpmOWAbNMHPKOeCZlrE0RyUc3AQo0Dco2nx/glAxrVJhRQS5pqDlVyhy5OU5LSOe21Nm/iiXNkEa1ed2ANUZx+wNsIYTqccNj0d1m12n6G7ivTH3dxfviYY/3jSCAFMIj+cJVdmLACJvqntPbPiuAYOfuwwLPm/MKC+eCCKG0EI5ggn2NzHfzZlkQ/GjF6s8nx6jA0Jf4HUiLdhlvS/njjWriCpOvp7hzVHqGh07KbmYyhAFFc/3FK4boXcs9Mkd2IEuGNHdNayP6dRzbKyHMXCH0h0x+hcrKe5X0ZS1Hsxpu5xur6NM4C0AZyjgS0fJQrC4txg87xovqaGWdtadWIKVx6NtOg5fDvVSJ/3YS050d6NGFQ6UPwO37rQuaSNbeNfEtqd/6W4k4Gng3kFbBEa8lMnjuIdC/fMdvp4="

notifications:
  email:
    on_success: never
    on_failure: always

before_install: source scripts/ci/environment.sh

install: make build

script: make test

after_success:
- ci-tag-build
- hub-push
- hub-update-readme
