addons:
  apt:
    packages:
    - realpath
language: python
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=joeblackwaslike
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=joeblackwaslike
  # DOCKER_PASS
  - secure: "GE05JaeJiiyLBbkS18xhJ6vkU81n2AZjYl9DqZV8cJZ8M70LxMYP1VtLHtdqMGMfGxVE6WbEs1Oiszs7XLJZIdZf2YbGqCJ/lVtKnfzDz+25+ffPpcmzuS1ZuZ8lkZKjXFDAVKpqTj6scD2FSDWRGA9E87M8vjcTgmc0uogOEta9Fo82yIBwrQ78UDyHcUxEVbD65IpLfBeEfvUQa+gfRdN/IXflhF/zjooULHe3SoHwyO7jU42GKL5W/kHmmmgs9oOBdhbLggU5RK5LD85AIo+1/jbQD1zgw5PZ1WszHOG3B9l53N5KhqyQysHdp3FIAuD5dewuPR+eunn9kH1dzu+jCxsrSn3Gc5aZeJhPG0tUBrSmxD2feMt+z26OqG9sp/yNWymwHj+36MerS3N49PlU3R+c2IHCb9h/rXwHKF8PEAbn2jyKLWF/VA7rLuT2swQNCWSviCxm9ZnJjbZxvtCfORf+kvm1c9YMpZvJ6xcAJ0NvcURGtlvFJmXNRXkCzhSBxIER/kUUQstXbMVm4AUI5VMGoOEM18mUkqWDN2wo40S7Hm2jKQx7y9tU1gD2QUK/1zno3MPlxdf63b0zqfkIP2Zu48kkpaN9aNadtE5NL41Vo1ZTK0yC60fKINr0EVb4N10aSLG3IGl9kWVqneHurGgeLAZwp09nYNU/dcc="

notifications:
  email:
    on_success: never
    on_failure: always

before_install: source scripts/ci/environment.sh

install: make build

script: make test

after_success:
- ci-tag-build
- hub-push
- hub-update-readme
